#Wekk 9 - Decision Tree C4.5

##1. Import Library

In [1]:
import numpy as pd
import pandas as pd

!pip install chefboost -q
from chefboost import Chefboost as chef

##2. Load Dataset

In [2]:
path = '/content/drive/MyDrive/Colab Notebooks/DATA MINING 3/week9/PlayTennis.csv'

df = pd.read_csv(path)
df.head()

    Outlook Temperature Humidity    Wind Play Tennis
0     Sunny         Hot     High    Weak          No
1     Sunny         Hot     High  Strong          No
2  Overcast         Hot     High    Weak         Yes
3      Rain        Mild     High    Weak         Yes
4      Rain        Cool   Normal    Weak         Yes

In [3]:
print('shape :', df.shape)
df.info()

shape : (14, 5)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Outlook      14 non-null     object
 1   Temperature  14 non-null     object
 2   Humidity     14 non-null     object
 3   Wind         14 non-null     object
 4   Play Tennis  14 non-null     object
dtypes: object(5)
memory usage: 688.0+ bytes

In [4]:
#show unique
for columnName, columnData in df.iteritems():
  print(f'Column name : {columnName}')
  print(f'Column unique : {set(columnData.values)} \n')

Column name : Outlook
Column unique : {'Sunny', 'Rain', 'Overcast'}

Column name : Temperature
Column unique : {'Cool', 'Hot', 'Mild'}

Column name : Humidity
Column unique : {'High', 'Normal'}

Column name : Wind
Column unique : {'Weak', 'Strong'}

Column name : Play Tennis
Column unique : {'Yes', 'No'}

##3. Create classifier model

In [6]:
#tentukan config 4.5
config = {'algorithm':'C4.5'}

#tentukan model c4.5 model di training set
c45_model = chef.fit(df, config, target_label='Play Tennis')

[INFO]:  1 CPU cores will be allocated in parallel running
C4.5  tree is going to be built...
-------------------------
finished in  0.5453619956970215  seconds
-------------------------
Evaluate  train set
-------------------------
Accuracy:  100.0 % on  14  instances
Labels:  ['No' 'Yes']
Confusion matrix:  [[5, 0], [0, 9]]
Precision:  100.0 %, Recall:  100.0 %, F1:  100.0 %

##4. show rules result

In [8]:
with open('/content/outputs/rules/rules.py',encoding='utf8') as f:
  for line in f:
    print(line.strip())

def findDecision(obj): #obj[0]: Outlook, obj[1]: Temperature, obj[2]: Humidity, obj[3]: Wind
# {"feature": "Outlook", "instances": 14, "metric_value": 0.9403, "depth": 1}
if obj[0] == 'Sunny':
# {"feature": "Humidity", "instances": 5, "metric_value": 0.971, "depth": 2}
if obj[2] == 'High':
return 'No'
elif obj[2] == 'Normal':
return 'Yes'
else: return 'Yes'
elif obj[0] == 'Rain':
# {"feature": "Wind", "instances": 5, "metric_value": 0.971, "depth": 2}
if obj[3] == 'Weak':
return 'Yes'
elif obj[3] == 'Strong':
return 'No'
else: return 'No'
elif obj[0] == 'Overcast':
return 'Yes'
else: return 'Yes'

##5. predict

In [14]:
#prediction berdasar row
r = int(input('select row: '))
print(f'Row: \n {df.loc[r]}')
print(f'\nPrediction: {chef.predict(c45_model,df.loc[r])}')

select row: 4
Row:
 Outlook          Rain
Temperature      Cool
Humidity       Normal
Wind             Weak
Play Tennis       Yes
Name: 4, dtype: object

Prediction: Yes

In [23]:
#prediction dengan inputan

outl = input('masukan outlook: ')
temp = input('masukan temperature: ')
humi = input('masukan humidity: ')
wind = input('masukan wind: ')

print(f'\nPrediction ?Playing Tenis : {chef.predict(c45_model, param=[outl,temp,humi,wind])}')

KeyboardInterrupt: ignored

#implementasi 2

In [22]:
path2 = '/content/drive/MyDrive/Colab Notebooks/DATA MINING 3/week9/bank-full.csv'

df2 = pd.read_csv(path2)
df2.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,Target
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

In [25]:
print('shape :', df2.shape)
df2.info()

shape : (45211, 17)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        45211 non-null  int64
 1   job        45211 non-null  object
 2   marital    45211 non-null  object
 3   education  45211 non-null  object
 4   default    45211 non-null  object
 5   balance    45211 non-null  int64
 6   housing    45211 non-null  object
 7   loan       45211 non-null  object
 8   contact    45211 non-null  object
 9   day        45211 non-null  int64
 10  month      45211 non-null  object
 11  duration   45211 non-null  int64
 12  campaign   45211 non-null  int64
 13  pdays      45211 non-null  int64
 14  previous   45211 non-null  int64
 15  poutcome   45211 non-null  object
 16  Target     45211 non-null  object
dtypes: int64(7), object(10)
memory usage: 5.9+ MB

In [29]:
#feature selection
cat = []
for col,val in df2.iteritems():
  if val.dtype =='object':
    cat.append(col)

df3 = df2[cat]

In [30]:
df3.head()

,job,marital,education,default,housing,loan,contact,month,poutcome,Target
0,management,married,tertiary,no,yes,no,unknown,may,unknown,no
1,technician,single,secondary,no,yes,no,unknown,may,unknown,no
2,entrepreneur,married,secondary,no,yes,yes,unknown,may,unknown,no
3,blue-collar,married,unknown,no,yes,no,unknown,may,unknown,no
4,unknown,single,unknown,no,no,no,unknown,may,unknown,no

In [35]:
#convert to numeric
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

df_feature_select = df3.copy()
for colName in df_feature_select:
  df_feature_select[colName]=le.fit_transform(df_feature_select[colName])

df_feature_select.head()

,job,marital,education,default,housing,loan,contact,month,poutcome,Target
0,4,1,2,0,1,0,2,8,3,0
1,9,2,1,0,1,0,2,8,3,0
2,2,1,1,0,1,1,2,8,3,0
3,1,1,3,0,1,0,2,8,3,0
4,11,2,3,0,0,0,2,8,3,0

In [38]:
corr = df_feature_select.corr()

corr_target = abs(corr['housing'])

relevant_features = corr_target[corr_target>0.1]
relevant_features

job        0.125363
housing    1.000000
contact    0.188123
month      0.271481
Target     0.139173
Name: housing, dtype: float64

In [43]:
sel_df = df3[['job','contact', 'month','Target','housing']]

In [44]:
sel_df.head()

            job  contact month Target housing
0    management  unknown   may     no     yes
1    technician  unknown   may     no     yes
2  entrepreneur  unknown   may     no     yes
3   blue-collar  unknown   may     no     yes
4       unknown  unknown   may     no      no

In [67]:
#split data

df_train = sel_df.loc[sel_df['housing']=='yes'].head(200)
df_train_no = sel_df.loc[sel_df['housing']=='no'].head(200)
df_train = df_train.append(df_train_no).reset_index().drop('index',1)

<ipython-input-67-2883d2b83fd4>:5: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  df_train = df_train.append(df_train_no).reset_index().drop('index',1)

In [68]:
df_test = sel_df.loc[sel_df['housing']=='yes'].tail(40)
df_test_no = sel_df.loc[sel_df['housing']=='no'].tail(40)
df_test = df_test.append(df_test_no).reset_index().drop('index',1)

<ipython-input-68-de6fd39067aa>:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  df_test = df_test.append(df_test_no).reset_index().drop('index',1)

In [63]:
for columnName, columnData in df_train.iteritems():
  print(f'Column name : {columnName}')
  print(f'Column unique : {set(columnData.values)} \n')

Column name : job
Column unique : {'retired', 'technician', 'unemployed', 'self-employed', 'unknown', 'services', 'entrepreneur', 'blue-collar', 'management', 'admin.', 'housemaid', 'student'}

Column name : contact
Column unique : {'unknown'}

Column name : month
Column unique : {'may'}

Column name : Target
Column unique : {'yes', 'no'}

Column name : housing
Column unique : {'yes', 'no'}

In [69]:
#tentukan config 4.5
config = {'algorithm':'C4.5'}

#tentukan model c4.5 model di training set
c45_model2 = chef.fit(df_train, config, target_label='housing')

[INFO]:  1 CPU cores will be allocated in parallel running
C4.5  tree is going to be built...
-------------------------
finished in  5.920750141143799  seconds
-------------------------
Evaluate  train set
-------------------------
Accuracy:  54.0 % on  400  instances
Labels:  ['yes' 'no']
Confusion matrix:  [[160, 144], [40, 56]]
Precision:  52.6316 %, Recall:  80.0 %, F1:  63.4921 %

In [ ]:
with open('/content/outputs/rules/rules.py',encoding='utf8') as f:
  for line in f:
    print(line.strip())

In [60]:
#prediction berdasar row
r = int(input('select row: '))
print(f'\nRow: \n {df_test.loc[r]}')
print(f'Actual: {df_test['housing'].loc[r]}')
print(f'\nPrediction: {chef.predict(c45_model2,df_test.loc[r])}')

SyntaxError: ignored

In [70]:
predicted = []
for r in df_test.index:
  predicted.append(chef.predict(c45_model2,df_test.loc[r]))

In [71]:
#evaluate

from sklearn.metrics import *
print(classification_report(df_test['housing'].values,predicted,zero_division=0))

              precision    recall  f1-score   support

          no       0.41      0.23      0.29        40
         yes       0.47      0.68      0.55        40

    accuracy                           0.45        80
   macro avg       0.44      0.45      0.42        80
weighted avg       0.44      0.45      0.42        80